apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: bg-rabbitmqcluster
spec:
  replicas: 3
  service:
    type: LoadBalancer
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: agentpool
            operator: In 
            values:
            - userpool2
